apiVersion: v1
kind: Pod
metadata:
  name: training-app
  labels:
    app: training
spec:
  containers:
  - name: training-app-container
    image: missalt/training:0.3
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10