apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-app
  labels:
    app: training
spec:
  replicas: 3
  selector:
    matchLabels:
      app: training
  template:
    metadata:
      labels:
        app: training
    spec:
      containers:
      - name: training-app-container
        image: missalt/training:1
        ports:
        - containerPort: 8080